[theme]
base = "light"
primaryColor = "#477968"
backgroundColor = "#F5F3ED"
secondaryBackgroundColor = "#FFFEFA"
textColor = "#253B35"
font = "sans serif"
borderColor = "#DCDFD3"
showWidgetBorder = true
